USE `DTUGRP16`;

DROP TRIGGER IF EXISTS client_before_insert;

DELIMITER //
CREATE TRIGGER client_before_insert
	BEFORE INSERT ON `DTUGRP16`.`Client` FOR EACH ROW
    BEGIN
		DECLARE ID INTEGER;
		SET ID = (SELECT CAST(SUBSTRING(ClientID, 1, 8) AS UNSIGNED) FROM `DTUGRP16`.`Client` ORDER BY ClientID DESC LIMIT 1);
        IF ID > 0 THEN
			SET ID = ID + 1;
			SET New.ClientID = RPAD(LPAD(ID, 8, '0'), 9, 'C');
		ELSE
			SET New.ClientID = '00000001C';
		END IF;
	END; //
DELIMITER ;      

DROP TRIGGER IF EXISTS client_before_insert;

DELIMITER //
CREATE TRIGGER banker_before_insert
	BEFORE INSERT ON Banker FOR EACH ROW
    BEGIN
		DECLARE ID INTEGER;
		SET ID = (SELECT CAST(SUBSTRING(BankerID, 1, 6) AS UNSIGNED) FROM Banker ORDER BY BankerID DESC LIMIT 1);
        IF ID > 0 THEN
			SET ID = ID + 1;
			SET New.BankerID = RPAD(LPAD(ID, 6, '0'), 7, 'B');
		ELSE
			SET New.BankerID = '000001B';
		END IF;
	END; //
DELIMITER ;    
